language: python
python:
  - "3.6"

install:
  - pip install coveralls pytest-cov pytest
  - pip install -e .

script:
  - python -m pytest -v --cov snapgene_utils --cov-report term-missing

after_success:
  - coveralls
